# Generated by Django 3.2.9 on 2021-11-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='pin_picture',
        ),
    ]
