# Generated by Django 3.2.9 on 2021-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0002_remove_pin_pin_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='pin_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
